{
	"id": "oval:com.redhat.cve:def:202456374",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "django: potential denial-of-service vulnerability in IPv6 validation (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2024-56374",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-56374",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: The CVE program describes this issue as: An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2025-01-14"
			},
			"cve": [
				{
					"text": "CVE-2024-56374",
					"cvss3": "5.8/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
					"cwe": "CWE-770",
					"href": "https://access.redhat.com/security/cve/CVE-2024-56374",
					"impact": "moderate",
					"public": "20250114"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"python-django",
							"python2-django"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:satellite:6.10",
					"cpe:/a:redhat:satellite:6.10::el7",
					"cpe:/a:redhat:satellite_capsule:6.10",
					"cpe:/a:redhat:satellite_capsule:6.10::el7"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844001",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844002",
										"comment": "python-django is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844003",
										"comment": "python2-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844004",
										"comment": "python2-django is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20134120009",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20134120010",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
