{
	"id": "oval:com.redhat.cve:def:202346136",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-werkzeug: high resource consumption leading to denial of service (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2023-46136",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-46136",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A resource consumption flaw was found in python-werkzeug. If a specially crafted file is uploaded by a remote attacker, it may cause a denial of service.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-03-11"
			},
			"cve": [
				{
					"text": "CVE-2023-46136",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-407",
					"href": "https://access.redhat.com/security/cve/CVE-2023-46136",
					"impact": "moderate",
					"public": "20231025"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Will not fix",
						"component": [
							"python-werkzeug"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:storage:3.5",
					"cpe:/a:redhat:storage:3.5:nfs:el8",
					"cpe:/a:redhat:storage:3.5:samba:el8",
					"cpe:/a:redhat:storage:3.5:server:el8"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:201718638003",
						"comment": "Red Hat Enterprise Linux 8 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202323934001",
						"comment": "python-werkzeug is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202323934002",
						"comment": "python-werkzeug is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:201718638004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
