{
	"id": "oval:com.redhat.rhsa:def:20237395",
	"version": "635",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2023:7395: python-setuptools security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2023:7395",
				"ref_url": "https://access.redhat.com/errata/RHSA-2023:7395",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2022-40897",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2022-40897",
				"source": "CVE"
			}
		],
		"description": "The python-setuptools package provides a collection of enhancements to Python distribution utilities allowing convenient building and distribution of Python packages.\n\nSecurity Fix(es):\n\n* pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py (CVE-2022-40897)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2023-11-21"
			},
			"cve": [
				{
					"text": "CVE-2022-40897",
					"cvss3": "5.9/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-185",
					"href": "https://access.redhat.com/security/cve/CVE-2022-40897",
					"impact": "moderate",
					"public": "20221222"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_e4s:8.6",
					"cpe:/a:redhat:rhel_e4s:8.6::appstream",
					"cpe:/a:redhat:rhel_e4s:8.6::highavailability",
					"cpe:/a:redhat:rhel_e4s:8.6::sap",
					"cpe:/a:redhat:rhel_e4s:8.6::sap_hana",
					"cpe:/o:redhat:rhel_e4s:8.6",
					"cpe:/o:redhat:rhel_e4s:8.6::baseos"
				]
			},
			"rights": "Copyright 2023 Red Hat, Inc.",
			"issued": {
				"date": "2023-11-21"
			},
			"bugzilla": [
				{
					"text": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
					"href": "https://bugzilla.redhat.com/2158559",
					"id": "2158559"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8.6 Extended Update Support"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395001",
										"comment": "platform-python-setuptools is earlier than 0:39.2.0-7.el8_6"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395002",
										"comment": "platform-python-setuptools is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395003",
										"comment": "python3-setuptools is earlier than 0:39.2.0-7.el8_6"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395004",
										"comment": "python3-setuptools is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395005",
										"comment": "python3-setuptools-wheel is earlier than 0:39.2.0-7.el8_6"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20237395006",
										"comment": "python3-setuptools-wheel is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20191992005",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
