{
	"id": "oval:com.redhat.cve:def:202123336",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python: Web cache poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a semicolon in query parameters (low)",
		"reference": [
			{
				"ref_id": "CVE-2021-23336",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2021-23336",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: The package python/cpython is vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter. \n            STATEMENT: The python36 component in the python36:3.6 module in Red Hat Enterprise Linux 8 is listed as not affected, as it does not contain Python interpreter or libraries. Packages of the python36 component only provide convenient links to the Python interpreter included in the non-modular python3 component's platform-python packages. Users of python36:3.6 module also need to check the entry for the python3 component to determine if their systems are affected.\n\nRed Hat Ceph Storage (RHCS) 3 ships an older version of python-django without the directly affected function, but which is still vulnerable to a similar attack involving the semi colon separator. Hence, impact has been rated as Low.\n\nAlthough Red Hat OpenStack Platform 13 & 16.1 both ship the affected code, since the proxy is controlled and configured by OpenStack, the impact has been lowered to Low. As a fix would require a substantial effort or commitment of time, no fix will be provided at this time.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Low",
			"updated": {
				"date": "2024-06-14"
			},
			"cve": [
				{
					"text": "CVE-2021-23336",
					"cvss3": "5.9/CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H",
					"cwe": "CWE-444",
					"href": "https://access.redhat.com/security/cve/CVE-2021-23336",
					"impact": "low",
					"public": "20210213"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Will not fix",
						"component": [
							"python-django",
							"python-django-bash-completion"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:ceph_storage:3",
					"cpe:/a:redhat:ceph_storage:3::el7"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201814574003",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201814574004",
										"comment": "python-django is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201814574001",
										"comment": "python-django-bash-completion is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201814574002",
										"comment": "python-django-bash-completion is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:201610745003",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:201610745004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
