{
	"id": "oval:com.redhat.rhsa:def:20204508",
	"version": "635",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2020:4508: libsolv security, bug fix, and enhancement update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2020:4508",
				"ref_url": "https://access.redhat.com/errata/RHSA-2020:4508",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2019-20387",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-20387",
				"source": "CVE"
			}
		],
		"description": "The libsolv packages provide a library for resolving package dependencies using a satisfiability algorithm.\n\nThe following packages have been upgraded to a later upstream version: libsolv (0.7.11). (BZ#1809106)\n\nSecurity Fix(es):\n\n* libsolv: out-of-bounds read in repodata_schema2id in repodata.c (CVE-2019-20387)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.3 Release Notes linked from the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2020-11-04"
			},
			"cve": [
				{
					"text": "CVE-2019-20387",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-125",
					"href": "https://access.redhat.com/security/cve/CVE-2019-20387",
					"impact": "moderate",
					"public": "20200121"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_eus:8.8",
					"cpe:/a:redhat:rhel_eus:8.8::appstream",
					"cpe:/a:redhat:rhel_eus:8.8::crb",
					"cpe:/a:redhat:rhel_eus:8.8::highavailability",
					"cpe:/a:redhat:rhel_eus:8.8::nfv",
					"cpe:/a:redhat:rhel_eus:8.8::realtime",
					"cpe:/a:redhat:rhel_eus:8.8::resilientstorage",
					"cpe:/a:redhat:rhel_eus:8.8::sap",
					"cpe:/a:redhat:rhel_eus:8.8::sap_hana",
					"cpe:/a:redhat:rhel_eus:8.8::supplementary",
					"cpe:/o:redhat:rhel_eus:8.8",
					"cpe:/o:redhat:rhel_eus:8.8::baseos"
				]
			},
			"rights": "Copyright 2020 Red Hat, Inc.",
			"issued": {
				"date": "2020-11-04"
			},
			"bugzilla": [
				{
					"text": "libsolv: out-of-bounds read in repodata_schema2id in repodata.c",
					"href": "https://bugzilla.redhat.com/1797072",
					"id": "1797072"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20204508001",
										"comment": "libsolv is earlier than 0:0.7.11-1.el8"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20193583002",
										"comment": "libsolv is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20204508003",
										"comment": "python3-solv is earlier than 0:0.7.11-1.el8"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20204508004",
										"comment": "python3-solv is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20191992005",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
