{
	"id": "oval:com.redhat.cve:def:202412254",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python: Unbounded memory buffering in SelectorSocketTransport.writelines() (important)",
		"reference": [
			{
				"ref_id": "CVE-2024-12254",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-12254",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A flaw was found in Python. In certain configurations, the `asyncio._SelectorSocketTransport.writelines()` method fails to signal the protocol to clear the write buffer when it approaches capacity. Because of this, protocols would not periodically drain the write buffer, potentially leading to a denial of service via memory exhaustion. \n            STATEMENT: This vulnerability likely impacts a small number of users. You must be using Python 3.12.0 or later, on Linux, using the asyncio module with protocols, and using .writelines() method which had new zero-copy-on-write behavior in Python 3.12.0 and later. If not all of these factors are true, then your usage of Python is unaffected.\n\n\nThis vulnerability is rated with an Important severity due to its potential for denial of service (DoS) attacks through memory exhaustion. By failing to signal the protocol to drain the write buffer when approaching the high-water mark, the affected `asyncio._SelectorSocketTransport.writelines()` method introduces a important flaw in flow control. This flaw can lead to uncontrolled growth of the buffer in long-running or high-throughput applications, which are typical in networked systems or event-driven architectures. Given that `asyncio` is widely used in performance-critical Python applications for handling asynchronous I/O, the impact of memory exhaustion could destabilize services, compromise system availability, and increase the risk of cascading failures, especially in production environments handling large-scale or untrusted inputs.\n            MITIGATION: Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Important",
			"updated": {
				"date": "2024-12-09"
			},
			"cve": [
				{
					"text": "CVE-2024-12254",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "(CWE-400|CWE-770)",
					"href": "https://access.redhat.com/security/cve/CVE-2024-12254",
					"impact": "important",
					"public": "20241206:1519"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"python3.12",
							"python3.12-debug",
							"python3.12-devel",
							"python3.12-idle",
							"python3.12-libs",
							"python3.12-rpm-macros",
							"python3.12-test",
							"python3.12-tkinter"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:8",
					"cpe:/a:redhat:enterprise_linux:8::appstream",
					"cpe:/a:redhat:enterprise_linux:8::crb",
					"cpe:/a:redhat:enterprise_linux:8::highavailability",
					"cpe:/a:redhat:enterprise_linux:8::nfv",
					"cpe:/a:redhat:enterprise_linux:8::realtime",
					"cpe:/a:redhat:enterprise_linux:8::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:8::sap",
					"cpe:/a:redhat:enterprise_linux:8::sap_hana",
					"cpe:/a:redhat:enterprise_linux:8::supplementary",
					"cpe:/o:redhat:enterprise_linux:8",
					"cpe:/o:redhat:enterprise_linux:8::baseos"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397007",
										"comment": "python3.12-test is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397008",
										"comment": "python3.12-test is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397009",
										"comment": "python3.12-tkinter is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397010",
										"comment": "python3.12-tkinter is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397013",
										"comment": "python3.12-debug is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397014",
										"comment": "python3.12-debug is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397023",
										"comment": "python3.12-devel is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397024",
										"comment": "python3.12-devel is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397035",
										"comment": "python3.12-libs is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397036",
										"comment": "python3.12-libs is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397025",
										"comment": "python3.12-idle is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397026",
										"comment": "python3.12-idle is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397037",
										"comment": "python3.12-rpm-macros is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397038",
										"comment": "python3.12-rpm-macros is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397005",
										"comment": "python3.12 is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20240397006",
										"comment": "python3.12 is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20052541003",
						"comment": "Red Hat Enterprise Linux 8 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
