{
	"id": "oval:com.redhat.rhsa:def:20242292",
	"version": "639",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2024:2292: python3.11 security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2024:2292",
				"ref_url": "https://access.redhat.com/errata/RHSA-2024:2292",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2023-27043",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-27043",
				"source": "CVE"
			}
		],
		"description": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple (CVE-2023-27043)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 9.4 Release Notes linked from the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-04-30"
			},
			"cve": [
				{
					"text": "CVE-2023-27043",
					"cvss3": "5.3/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
					"cwe": "CWE-20",
					"href": "https://access.redhat.com/security/cve/CVE-2023-27043",
					"impact": "moderate",
					"public": "20230419"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_eus:9.4",
					"cpe:/a:redhat:rhel_eus:9.4::appstream",
					"cpe:/a:redhat:rhel_eus:9.4::crb",
					"cpe:/a:redhat:rhel_eus:9.4::highavailability",
					"cpe:/a:redhat:rhel_eus:9.4::nfv",
					"cpe:/a:redhat:rhel_eus:9.4::realtime",
					"cpe:/a:redhat:rhel_eus:9.4::resilientstorage",
					"cpe:/a:redhat:rhel_eus:9.4::sap",
					"cpe:/a:redhat:rhel_eus:9.4::sap_hana",
					"cpe:/a:redhat:rhel_eus:9.4::supplementary",
					"cpe:/o:redhat:rhel_eus:9.4",
					"cpe:/o:redhat:rhel_eus:9.4::baseos"
				]
			},
			"rights": "Copyright 2024 Red Hat, Inc.",
			"issued": {
				"date": "2024-04-30"
			},
			"bugzilla": [
				{
					"text": "python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
					"href": "https://bugzilla.redhat.com/2196183",
					"id": "2196183"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 9"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292001",
										"comment": "python3.11 is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585002",
										"comment": "python3.11 is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292003",
										"comment": "python3.11-debug is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585004",
										"comment": "python3.11-debug is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292005",
										"comment": "python3.11-devel is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585006",
										"comment": "python3.11-devel is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292007",
										"comment": "python3.11-idle is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585008",
										"comment": "python3.11-idle is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292009",
										"comment": "python3.11-libs is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585010",
										"comment": "python3.11-libs is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292011",
										"comment": "python3.11-test is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585012",
										"comment": "python3.11-test is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20242292013",
										"comment": "python3.11-tkinter is earlier than 0:3.11.7-1.el9"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20233585014",
										"comment": "python3.11-tkinter is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.rhba:tst:20223945011",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20223945012",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
