{
	"id": "oval:com.redhat.cve:def:20242199",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "389-ds-base: Malformed userPassword may cause crash at do_modify in slapd/modify.c (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2024-2199",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-2199",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A denial of service vulnerability was found in 389-ds-base ldap server. This issue may allow an authenticated user to cause a server crash while modifying `userPassword` using malformed input. \n            STATEMENT: LDAP servers are not usually exposed to the open internet, requiring adjacent connectivity for a successful attack. This issue also requires a compromised user account to perform the attack. Therefore, this flaw is rated as a Moderate severity.\n            MITIGATION: Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-05-29"
			},
			"cve": [
				{
					"text": "CVE-2024-2199",
					"cvss3": "5.7/CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-20",
					"href": "https://access.redhat.com/security/cve/CVE-2024-2199",
					"impact": "moderate",
					"public": "20240528"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"389-ds-base",
							"389-ds-base-libs",
							"python3-lib389"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:9",
					"cpe:/a:redhat:enterprise_linux:9::appstream",
					"cpe:/a:redhat:enterprise_linux:9::crb",
					"cpe:/a:redhat:enterprise_linux:9::highavailability",
					"cpe:/a:redhat:enterprise_linux:9::nfv",
					"cpe:/a:redhat:enterprise_linux:9::realtime",
					"cpe:/a:redhat:enterprise_linux:9::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:9::sap",
					"cpe:/a:redhat:enterprise_linux:9::sap_hana",
					"cpe:/a:redhat:enterprise_linux:9::supplementary",
					"cpe:/o:redhat:enterprise_linux:9",
					"cpe:/o:redhat:enterprise_linux:9::baseos"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517007",
										"comment": "python3-lib389 is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517008",
										"comment": "python3-lib389 is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517009",
										"comment": "389-ds-base-libs is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517010",
										"comment": "389-ds-base-libs is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517011",
										"comment": "389-ds-base is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20223517012",
										"comment": "389-ds-base is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20052541003",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
