{
	"id": "oval:com.redhat.rhsa:def:20242559",
	"version": "638",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2024:2559: python-jwcrypto security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2024:2559",
				"ref_url": "https://access.redhat.com/errata/RHSA-2024:2559",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2024-28102",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-28102",
				"source": "CVE"
			}
		],
		"description": "The python-jwcrypto package provides Python implementations of the JSON Web Key (JWK), JSON Web Signature (JWS), JSON Web Encryption (JWE), and JSON Web Token (JWT) JOSE (JSON Object Signing and Encryption) standards.\n\nSecurity Fix(es):\n\n* python-jwcrypto: malicious JWE token can cause denial of service (CVE-2024-28102)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-04-30"
			},
			"cve": [
				{
					"text": "CVE-2024-28102",
					"cvss3": "6.8/CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:N/A:H",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2024-28102",
					"impact": "moderate",
					"public": "20240308"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:9",
					"cpe:/a:redhat:enterprise_linux:9::appstream",
					"cpe:/a:redhat:enterprise_linux:9::crb",
					"cpe:/a:redhat:enterprise_linux:9::highavailability",
					"cpe:/a:redhat:enterprise_linux:9::nfv",
					"cpe:/a:redhat:enterprise_linux:9::realtime",
					"cpe:/a:redhat:enterprise_linux:9::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:9::sap",
					"cpe:/a:redhat:enterprise_linux:9::sap_hana",
					"cpe:/a:redhat:enterprise_linux:9::supplementary",
					"cpe:/o:redhat:enterprise_linux:9",
					"cpe:/o:redhat:enterprise_linux:9::baseos"
				]
			},
			"rights": "Copyright 2024 Red Hat, Inc.",
			"issued": {
				"date": "2024-04-30"
			},
			"bugzilla": [
				{
					"text": "python-jwcrypto: malicious JWE token can cause denial of service",
					"href": "https://bugzilla.redhat.com/2268758",
					"id": "2268758"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 9"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20052541003",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					},
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20242559001",
						"comment": "python3-jwcrypto is earlier than 0:0.8-5.el9_4"
					},
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20242559002",
						"comment": "python3-jwcrypto is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
