{
  "id": "oval:com.redhat.cve:def:202324580",
  "version": "636",
  "class": "vulnerability",
  "metadata": {
    "title": "Potential denial-of-service vulnerability in file uploads (moderate)",
    "reference": [
      {
        "ref_id": "CVE-2023-24580",
        "ref_url": "https://access.redhat.com/security/cve/CVE-2023-24580",
        "source": "CVE"
      }
    ],
    "description": "DOCUMENTATION: A memory exhaustion flaw was found in the python-django package. This issue occurs when passing certain inputs, leading to a system crash and denial of service.",
    "advisory": {
      "from": "secalert@redhat.com",
      "severity": "Moderate",
      "updated": {
        "date": "2023-08-21"
      },
      "cve": [
        {
          "text": "CVE-2023-24580",
          "cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "cwe": "CWE-400",
          "href": "https://access.redhat.com/security/cve/CVE-2023-24580",
          "impact": "moderate",
          "public": "20230214:0900"
        }
      ],
      "affected": {
        "resolution": [
          {
            "state": "Affected",
            "component": [
              "python-django20",
              "python-django20-bash-completion",
              "python3-django20"
            ]
          }
        ]
      },
      "affected_cpe_list": {
        "cpe": [
          "cpe:/a:redhat:openstack:16.2",
          "cpe:/a:redhat:openstack:16.2::el8"
        ]
      },
      "issued": {}
    },
    "affected": {}
  },
  "criteria": {
    "operator": "OR",
    "criterias": [
      {
        "operator": "AND",
        "criterias": [
          {
            "operator": "OR",
            "criterias": [
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064003",
                    "comment": "python-django20 is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064004",
                    "comment": "python-django20 is signed with Red Hat redhatrelease2 key"
                  }
                ]
              },
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064005",
                    "comment": "python3-django20 is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064006",
                    "comment": "python3-django20 is signed with Red Hat redhatrelease2 key"
                  }
                ]
              },
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064001",
                    "comment": "python-django20-bash-completion is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202023064002",
                    "comment": "python-django20-bash-completion is signed with Red Hat redhatrelease2 key"
                  }
                ]
              }
            ]
          }
        ],
        "criterions": [
          {
            "test_ref": "oval:com.redhat.cve:tst:20178761011",
            "comment": "Red Hat Enterprise Linux 8 is installed"
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:com.redhat.cve:tst:20178761012",
        "comment": "Red Hat Enterprise Linux must be installed"
      }
    ]
  }
}
