{
	"id": "oval:com.redhat.cve:def:202240899",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "remote attackers can cause denial of service via crafted Set-Cookie header from malicious web server (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2022-40899",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2022-40899",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A denial of service flaw was found in Python Charmers Future. This flaw allows an attacker to send a specially crafted Set-Cookie header in an HTTP request, resulting in a loss of system availability.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2023-10-18"
			},
			"cve": [
				{
					"text": "CVE-2022-40899",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2022-40899",
					"impact": "moderate",
					"public": "20221221"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Will not fix",
						"component": [
							"python3-future"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openstack:16.1",
					"cpe:/a:redhat:openstack:16.1::el8"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20178761011",
						"comment": "Red Hat Enterprise Linux 8 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202240899001",
						"comment": "python3-future is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202240899002",
						"comment": "python3-future is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20178761012",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
