{
	"id": "oval:com.redhat.cve:def:202434069",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-werkzeug: user may execute code on a developer's machine (important)",
		"reference": [
			{
				"ref_id": "CVE-2024-34069",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-34069",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A flaw was found in Werkzeug, where an attacker may be able to execute code on a developer's machine under some circumstances. This issue requires the attacker to get the developer to interact with a domain and subdomain they control and enter the debugger PIN; if they are successful, it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger. \n            STATEMENT: Werkzeug's debugger allows an attacker to potentially execute code on a developer's machine. This can occur if the attacker tricks the developer into interacting with a controlled domain and subdomain and entering the debugger PIN. Although the debugger is meant to run locally, successful exploitation can give the attacker access to it by guessing a specific URL that triggers the debugger. The severity is rate as IMPORTANT because this flaw can potentially impacts confidentiality, integrity, and availability if the attacker can gain control.\n            MITIGATION: Red Hat has investigated whether a possible mitigation exists for this issue, and has not been able to identify a practical example. Please update the affected package as soon as possible.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Important",
			"updated": {
				"date": "2024-08-30"
			},
			"cve": [
				{
					"text": "CVE-2024-34069",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
					"cwe": "CWE-352",
					"href": "https://access.redhat.com/security/cve/CVE-2024-34069",
					"impact": "important",
					"public": "20240506"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Out of support scope",
						"component": [
							"python-werkzeug"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_extras_other:7"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20140047029",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202323934001",
						"comment": "python-werkzeug is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:202323934002",
						"comment": "python-werkzeug is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20140047030",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
