{
	"id": "oval:com.redhat.cve:def:202341164",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-django: Potential denial of service vulnerability in  ``django.utils.encoding.uri_to_iri()`` (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2023-41164",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-41164",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: An uncontrolled resource consumption vulnerability was found in Django. Feeding certain inputs with a very large number of Unicode characters to the URI to IRI encoder function can lead to a denial of service.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-04-23"
			},
			"cve": [
				{
					"text": "CVE-2023-41164",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2023-41164",
					"impact": "moderate",
					"public": "20230904"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Out of support scope",
						"component": [
							"python-django",
							"python3-django"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openstack:17.1",
					"cpe:/a:redhat:openstack:17.1::el9"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164001",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164002",
										"comment": "python-django is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164003",
										"comment": "python3-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164004",
										"comment": "python3-django is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:202234038003",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:202234038004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
