{
	"id": "oval:com.redhat.cve:def:202438875",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-django: Potential denial-of-service in django.utils.html.urlize() (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2024-38875",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-38875",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A vulnerability was found in the Django framework's urlize and urlizetrunc functions, where an attacker can input a certain string containing a large number of brackets, leads to a potential denial of service when the application attempts to process the excessive input. \n            \n            MITIGATION: Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-10-07"
			},
			"cve": [
				{
					"text": "CVE-2024-38875",
					"cvss3": "5.3/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"cwe": "CWE-1287",
					"href": "https://access.redhat.com/security/cve/CVE-2024-38875",
					"impact": "moderate",
					"public": "20240726:0626"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"python-django",
							"python3-django"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openstack:17.1",
					"cpe:/a:redhat:openstack:17.1::el9"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164001",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164002",
										"comment": "python-django is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164003",
										"comment": "python3-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202341164004",
										"comment": "python3-django is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:202234038003",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:202234038004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
