{
	"id": "oval:com.redhat.cve:def:201911324",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-urllib3: Certification mishandle when error should be thrown (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2019-11324",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-11324",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: The MITRE CVE dictionary describes this issue as: The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument. \n            STATEMENT: This issue did not affect the versions of python-urllib3 as shipped with Red Hat Enterprise Linux 6, and 7 as the older code shipped there did not load the system certificates.\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected Critical and Important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package.\n            MITIGATION: The urllib3 package is used by elastic-curator, which is deployed in the ose-logging-curator, and used by the optional logging feature in OpenShift Container Platform (OCP). Therefore OCP 3.11 users can mitigate this issue by not deploying and using the Curator logging feature. \n\nIn OCP 4 urllib3 is also used by several Ansible Play Book images built with the Operator SDK and available for installation in OCP 4 including openshift-enterprise-ansible-operator and ose-metering-ansible-operator. Therefore those operators should not be deployed in order to mitigate this issue in OCP 4.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2021-12-14"
			},
			"cve": [
				{
					"text": "CVE-2019-11324",
					"cvss3": "7.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
					"cwe": "CWE-295",
					"href": "https://access.redhat.com/security/cve/CVE-2019-11324",
					"impact": "moderate",
					"public": "20190417"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"python-urllib3"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:storage:3",
					"cpe:/a:redhat:storage:3.1",
					"cpe:/a:redhat:storage:3.1:bigdata:el6",
					"cpe:/a:redhat:storage:3.1:console:el6",
					"cpe:/a:redhat:storage:3.1:nagios:el6",
					"cpe:/a:redhat:storage:3.1:nfs:el6",
					"cpe:/a:redhat:storage:3.1:samba:el6",
					"cpe:/a:redhat:storage:3.1:server:el6",
					"cpe:/a:redhat:storage:3.2",
					"cpe:/a:redhat:storage:3.2:nagios:el6",
					"cpe:/a:redhat:storage:3.2:nfs:el6",
					"cpe:/a:redhat:storage:3.2:samba:el6",
					"cpe:/a:redhat:storage:3.2:server:el6",
					"cpe:/a:redhat:storage:3.3",
					"cpe:/a:redhat:storage:3.3:nagios:el6",
					"cpe:/a:redhat:storage:3.3:nfs:el6",
					"cpe:/a:redhat:storage:3.3:samba:el6",
					"cpe:/a:redhat:storage:3.3:server:el6",
					"cpe:/a:redhat:storage:3.4",
					"cpe:/a:redhat:storage:3.4:samba:el6",
					"cpe:/a:redhat:storage:3.4:server:el6",
					"cpe:/a:redhat:storage:3.5",
					"cpe:/a:redhat:storage:3.5:samba:el6",
					"cpe:/a:redhat:storage:3.5:server:el6",
					"cpe:/a:redhat:storage:3:bigdata:el6",
					"cpe:/a:redhat:storage:3:client:el6",
					"cpe:/a:redhat:storage:3:console:el6",
					"cpe:/a:redhat:storage:3:nagios:el6",
					"cpe:/a:redhat:storage:3:nfs:el6",
					"cpe:/a:redhat:storage:3:samba:el6",
					"cpe:/a:redhat:storage:3:server:el6"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:201610089007",
						"comment": "Red Hat Enterprise Linux 6 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:201820060001",
						"comment": "python-urllib3 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:201820060002",
						"comment": "python-urllib3 is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:201610089008",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
